### ISSUE TITLE
RFC - Adding a `:prefix` option to `embedded_templates/2`

### ISSUE THREAD

**Issue by kyleboe** [phoenixframework/phoenix_template#5]
### Use Case
When building up a tree of templates for rendering templates (like emails in the example below), it would be nice to use a `:prefix` option to generate function names in nested directories without having to leave component module files in said nested directories. 
```elixir
defmodule EmailHTML do
  use Phoenix.Component

  embed_templates "templates/email/admin/*.html", prefix: "admin_", suffix: "_html"
  embed_templates "templates/email/user/*.html", prefix: "user_", suffix: "_html"
end
```

### Implementation
If I am understanding how things are currently implemented, I believe this would involve modifying this section of code here: https://github.com/phoenixframework/phoenix_template/blob/d6098a7f647911f68149196c7ec19c9fba935a85/lib/phoenix/template.ex#L102-L119

to look something like this:
```elixir
  defmacro embed_templates(pattern, opts \\ []) do
    quote bind_quoted: [pattern: pattern, opts: opts] do
      Phoenix.Template.compile_all(
        &Phoenix.Template.__embed__(&1, opts[:prefix], opts[:suffix]),
        Path.expand(opts[:root] || __DIR__, __DIR__),
        pattern
      )
    end
  end

  @doc false
  def __embed__(path, prefix, suffix) do
      rootname = path
        |> Path.basename()
        |> Path.rootname()
        |> Path.rootname()
      (prefix || "")
      |> Kernel.<>(rootname)
      |> Kernel.<>(suffix || "")
  end
``` 

### Acknowledgements
Admittedly, I am relatively new to Phoenix/Elixir rendered views. If I am approaching this problem incorrectly, or am unaware of some far-reaching implications this change may have, I would gladly welcome correction to my approach.

**Comment by josevalim** [comment]
Hi @kyleboe, welcome!  Your changes are good. But is there any reason to not have them all as `admin_foo.html.heex` and `user_bar.html.heex` in a single directory instead?

**Comment by kyleboe** [comment]
Wow thanks for the fast response! And no, that totally makes sense, changing the file names and having them in a single directory would 100% do the trick. My reasoning in favor of having a directory structure is to cognitively separate things for a developer. Not sure if that is worth a change like this though. If you don't think so, I'm fine to close this out. :+1:  I just figured posing the question was better than leaving it un-asked.

**Comment by josevalim** [comment]
I think what you proposed makes sense and it is a change we can do in the future, but I would collect more use cases before committing to it. :) Thanks!
